### PR TITLE
Support other separators

### PR DESCRIPTION
**Pull request by chris48s**
Based on the comments in issue #117 I've made a start on this.
There are several places where work needs to be done in order to fully support other separator characters:

- [x] Open
- [x] Save
- [x] Save As
- [x] Drag & Drop
- [x] Export as Datapackage
- [x] Github
- [x] CsvLint

I'll tick them off as I get them done. Once I'm happy for final review/merge I will remove the WIP tag, but feel free to provide review or comments on what I've done so far as I'm working on it.

### CODE REVIEW

**Comment by chris48s** [comment]
Reckon this is good for review now so I've removed WIP. For the moment, I've supported semicolon and tab as alternative separators but it is relatively easy to add more presets for other file types by adding additional objects to the `formats` object in `file-actions.js`.

Hopefully this is all ok. If you need anything changed, let me know.

Merging this should close issues #117 and #32 (dupes).

Cheers,
Chris

**Comment by pezholio** [comment]
This is amazing work, thanks! 🎉

I'll review properly tomorrow,  but looks good. Thanks! 👍🏻

**Comment by pezholio** [comment]
This is great, and I'm happy to merge as is. I'm going to open another issue about specifying other separators too.

**Comment by pezholio** [comment]
This is now built and deployed at https://github.com/theodi/comma-chameleon/releases/tag/0.4.4 Thanks again! 👍

**Pull request merged**
