### PR TITLE
Enhancement prebaked tdd suite

### PR DESCRIPTION
**Pull request by quadrophobiac**
[Electron-Mocha](https://github.com/jprichardson/electron-mocha) has been adopted for testing, it enables both DOM and node.js testing and provides command line options to enable testing of both renderer and runtime (respectively) aspects of an electron application

to run tests for the main (i.e. runtime) javascript:
    ```electron-mocha app/test/main/```

to run tests for the renderer (i.e. client facing/side) javascript:
    ```electron-mocha --renderer app/test/renderer/```

Incorporating mocha prompted refactoring the contents of `comma-chameleon/*.js` and a change in javascript management on `views/index.html`. A new index.js loads all the scripts that run the application, and almost all `ipc.on()` have been refactored into this file. This is a bit of a trade off in terms of code legibility, but was necessary for modularising the apps. `Menu.js` is still loaded by <script> tags for the time being

Testing DOM with electon-mocha follows the same invocation and declaration patterns as [jsdom()](https://www.npmjs.com/package/mocha-jsdom)

### CODE REVIEW

**Comment by pezholio** [comment]
I get an error when trying to running the tests:

```
child_process.js:909
      throw new TypeError('Incorrect value for stdio stream: ' + stdio);
            ^
TypeError: Incorrect value for stdio stream: inherit
    at child_process.js:909:13
    at Array.reduce (native)
    at ChildProcess.spawn (child_process.js:864:17)
    at exports.spawn (child_process.js:723:9)
    at runElectron (/usr/local/lib/node_modules/electron-mocha/bin/electron-mocha:24:18)
    at /usr/local/lib/node_modules/electron-mocha/bin/electron-mocha:17:28
    at /usr/local/lib/node_modules/electron-mocha/node_modules/which/which.js:81:18
    at Object.oncomplete (fs.js:107:15)

```

**Comment by quadrophobiac** [comment]
So I have made some changes to the dependency management to ensure that it works without npm tinkering  
Testing this may require downloading the repo into a fresh directory - I think when we were developing this we made a lot of additions via npm that weren't persisted. I have tested it and it works
```
brew install node
npm install
cd app/
bower install
```
then to test, return to root directory and run
```
electron-mocha app/test/main/ # run tests for the runtime components provided by Electron
electron-mocha --renderer app/test/renderer/ # run tests that execute client side
```

**Comment by quadrophobiac** [comment]
Have amended the process for calling tests to take account that README installation instructions do not install electron-mocha or electron-prebuilt globally (as is the preferred for both modules). Therefore some `npm run` scripts handle the invocation of electron mocha tests

**Comment by quadrophobiac** [comment]
@pezholio @Floppy I have made some further additions to this PR which fixes a couple of things
The way tests are invoked (see (comment)[https://github.com/theodi/comma-chameleon/pull/76#issuecomment-150247139] ) - these changes should resolve any module dependencies encountered on a fresh install of this repo.
I also fleshed out all the specs that were initially written so that they are actually testing Comma Chameleon using the conventions of chai and the way in which electron-mocha relates to the 'browser-renderer' separation of the Electron runtime
There are no breaking changes - the app can still be run by using `electron .` or `electron app` (depending on the directory one is when issuing the command).
I asked @pkqk to review the commit log I had in this - some of the earlier commits could do with truncating the initial sentence to < 50 chars, but I haven't done this yet because some of my comments and subsequent commits foolishly referenced prior commits via hyperlinks and those links will break on a rebase - if you'd like to see the rebase before merging let me know

**Comment by Floppy** [comment]
@pezholio reckon we can merge this in?

**Comment by pezholio** [comment]
@quadrophobiac FINALLY got chance to look this over. Think I understand what's going on now 😄  Soz for the HUGE delay!!!

**Pull request merged**
