### PR TITLE
add support for custom formats

### LINKED ISSUE #122: Allow manual specification of more esoteric seperators
Thanks to #120 - we can now save CSVs with tab and semicolon separators. It's a bit of an edge case, but it might be nice to have another option to specify custom separators (💩, ☃ etc). This could be a 'Custom separator...' menu option that spawns a new window, or something that could be set in a user's preferences that would create a new menu option (not sure if this is possible though - should be in theory)

### PR DESCRIPTION
**Pull request by chris48s**
This PR adds a dialog allowing the user to specify custom a separator and delimiter before opening or saving a file.

Finally all that data I have in :hankey:SV format comes into play! :)

Closes #122

### CODE REVIEW

**Comment by chris48s** [comment]
Rebased onto master to resolve conflict

**Comment by pezholio** [comment]
This works great, apart from (on OSX at least) once you save a file with a custom format, you have to close the `Custom` window that spawns. The following seems to work:

Setting up an optional callback in `saveFileAs`:

```
function saveFileAs(format, window, callback) {
  if (!window) {
    var window = BrowserWindow.getFocusedWindow();
  }
  Dialog.showSaveDialog({ filters: format.filters }, function (fileName) {
    if (fileName === undefined) return;
    window.webContents.send('saveData', fileName, format);
    utils.enableSave();
    window.format = format;
    if (callback) callback();
  });
}
```

Then adding a callback in `saveAsCustom` which closes the dialog like so:

```
  ipc.once('formatSelected', function(event, data) {
    var format = makeCustomFormat(data.separator, data.delimiter);
    saveFileAs(format, window, function() {
      dialog.close();
    });
  });
```

I'm going to look at adding you as a contributor to make this sort of collaboration easier in the future. I might even move Comma Chameleon to its own organisation if the ODI folks are OK with it, given I don't work there anymore 😄

**Comment by chris48s** [comment]
Odd - on linux calling `window.close()` [here](https://github.com/chris48s/comma-chameleon/blob/c27abd5fb2297013b19d595386fa827bb19dd3d5/views/views-content/custom_format.html#L47) closes it correctly.
I will have a bash at implementing your solution and update.
Cheers

**Comment by chris48s** [comment]
If we do it like this and move the `.close()` operation to the start of the start of the `'formatSelected'` handler (but before we create the open/save dialog), does that solve it for you? Or is it important that we call `Dialog.showSaveDialog()` / `Dialog.showOpenDialog()` before we try to close the `Custom` dialog? In principle, they don't need to be open at the same time as we've already got the data we need from the custom dialog before we call `Dialog.showSaveDialog()` / `Dialog.showOpenDialog()`.

Also, does the cancel button work for you (i.e: does [this](https://github.com/chris48s/comma-chameleon/blob/c27abd5fb2297013b19d595386fa827bb19dd3d5/views/views-content/custom_format.html#L36) `window.close()` statement execute correctly on your platform?)

**Comment by pezholio** [comment]
Ah yeah, that works. I missed the `window.close()` call in the frontend code, so that's why I had to implement the callback. I'm happy with this now, so will merge and push up a new release!

**Pull request merged**
