### PR TITLE
Add cells with tab and enter

### PR DESCRIPTION
**Pull request by pezholio**
After some discussion in #68, I've added the ability to add rows and columns via `tab` and `enter`. When a user reaches the far right of the table and tries to `tab` into a non-existent cell, a new column is created. `enter` does a similar thing, but with rows.

@chris48s I feel like this complements #128, so if you're happy, I'll merge #128, and then we'll get this in and push a release out.

### CODE REVIEW

**Comment by chris48s** [comment]
Yep in principle, this is good and definitely chimes with what users are expecting/asking for. I was a bit worried about overloading `Enter` with too many functions/making the behaviour inconsistent but getting rid of the toggle select/input mode deals with that.

In terms of your implementation, `Tab` seems fine but I am getting some strange behaviour with `Enter`. Hopefully this gives you a reproducable case - the 'insert row' operations are done by pressing `Enter` in this example:

gifrecord_2016-12-13_190039

**Comment by chris48s** [comment]
This also hijacks the `Shift+Tab` key combo.

If you press `Shift+Tab` in the rightmost column, it both inserts a column to the right and moves the cursor one cell to the left. In any other cell it just moves the cursor one cell left.

**Comment by pezholio** [comment]
Cool, well spotted. Both of those issues are fixed now :+1:

I was thinking that when creating a new row with enter, it would make sense to skip to the start of the new row. I'm gonna look at that now.

**Comment by pezholio** [comment]
This PR also fixes some of the inconsistencies with failing tests, as I understand a bit more about Mocha than when I started. If you're having any issues with the build, you might want to cherry pick https://github.com/theodi/comma-chameleon/pull/129/commits/7b98dc500c19b07d3111e9a93fd55412688c0f93

**Pull request merged**
